name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "backend/**"

env:
  IMAGE_NAME: backend-medisync
  DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
jobs:
  # debug:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Print trigger info
  #     run: |
  #       echo "🔍 Event name: ${{ github.event_name }}"
  #       echo "📂 Changed files:"
  #       echo "${{ toJSON(github.event.commits.*.modified) }}"
  #       echo "🔄 Workflow triggered successfully!"

    build:
     
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./backend

      steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build  -t $DOCKER_USERNAME/$IMAGE_NAME:$GITHUB_SHA -t $DOCKER_USERNAME/$IMAGE_NAME:latest .
