name: Frontend Docker Image CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ci.yaml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-ci.yaml"

env:
  IMAGE_NAME: frontend-medisync
  DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build the Docker image
        run: docker build -t $DOCKER_USERNAME/$IMAGE_NAME:$GITHUB_SHA -t $DOCKER_USERNAME/$IMAGE_NAME:latest .

      - name: Push the Docker image
        run: |
          docker push $DOCKER_USERNAME/$IMAGE_NAME:$GITHUB_SHA
          docker push $DOCKER_USERNAME/$IMAGE_NAME:latest